### ISSUE TITLE
`googleplayinstant_read_instant_app_data()` implementation missing in *.java

### ISSUE THREAD

**Issue by shichen85** [YoYoGames/GMEXT-GooglePlayInstant#1]
### Description

The GML code referenced the extension function `googleplayinstant_read_instant_app_data()`, but it is not seen in the extension's `*.java` file. 

https://github.com/YoYoGames/GMEXT-GooglePlayInstant/blob/8d7dfac1c78ea851536366c414511b8772956492/source/GooglePlayInstant_gml/objects/Obj_GooglePlayInstant/Other_70.gml#L29-L30

Is this function implemented outside of the `*.java` file?

### Steps To Reproduce

1. Start GameMaker
2. 
3. 
4. See the issue

### How reliably can you recreate this issue using your steps above?

Always

### Which version of GameMaker are you reporting this issue for?

Monthly, LTS, Beta

### Which platform(s) are you seeing the problem on?

Android

### Compiler Log File

- [X] I have attached my compiler log in a text file

### Sample .yyz File

- [ ] I have attached a small sample project

**Comment by jzavala-YYG** [comment]
Hello @shichen85:

Sorry for that, **_googleplayinstant_get_instant_app_data()_** and **_googleplayinstant_read_instant_app_data()_** are not completed, are you looking use it? what are you expectations?

Regards

**Comment by shichen85** [comment]
> Hello @shichen85:
> 
> Sorry for that, **_googleplayinstant_get_instant_app_data()_** and **_googleplayinstant_read_instant_app_data()_** are not completed, are you looking use it? what are you expectations?
> 
> Regards

Hello @jzavala-YYG, thanks for looking into this. I am actually looking for ways to pass buffers back and forth between GML and the Java extension, and I saw that `googleplayinstant_read_instant_app_data()` was passing a GML buffer to the Java side, so I was curious about the Java side implementation on how it can consume the GML buffer, or pass Java `byte[]` back to the GML side.

**Comment by jzavala-YYG** [comment]
@shichen85 

Ah okok, it's once you know how to do it, basically in this way:

GML:

```
	var buff = buffer_create(1024,buffer_fixed,1)
        //Write the buffer here....
        my_buff_function(buffer_get_address(buff))
        //Read in the buffer here....
        buffer_delete(buff)
```

Java:
```
	public void my_buff_function(ByteBuffer bytes)
	{
        //At this point you can write or read the buffer
	}
```
Note:  At the moment of define this function In the extension you should define the ByteBuffer argument as String argument.

I hope it help you.

Regards

**Comment by shichen85** [comment]
> @shichen85
> 
> Ah okok, it's once you know how to do it, basically in this way:
> 
> GML:
> 
> ```
> 	var buff = buffer_create(1024,buffer_fixed,1)
>         //Write the buffer here....
>         my_buff_function(buffer_get_address(buff))
>         //Read in the buffer here....
>         buffer_delete(buff)
> ```
> 
> Java:
> 
> ```
> 	public void my_buff_function(ByteBuffer bytes)
> 	{
>         //At this point you can write or read the buffer
> 	}
> ```
> 
> Note: At the moment of define this function In the extension you should define the ByteBuffer argument as String argument.
> 
> I hope it help you.
> 
> Regards

@jzavala-YYG Thank you! That's much simpler than I thought, which would be very helpful. Out of curiosity, I saw another implementation in the GMEXT-Bluetooth extension, where `RunnerJNILib.bufferGetByteBuffer` is used to convert the GML buffer handle to Java `ByteBuffer`:  https://github.com/YoYoGames/GMEXT-Bluetooth/blob/e3b25e5a5b3cd1efd8bb9e148167e570cc0c9175/source/Bluetooth_gml/extensions/Bluetooth/AndroidSource/Java/Bluetooth.java#L442C16-L442C41

Is `buffer_get_address()` a more modern implementation compared to `RunnerJNILib.bufferGetByteBuffer`?

**Comment by jzavala-YYG** [comment]
**_RunnerJNILib.bufferGetByteBuffer_** it's better.
